"""Standalone async Python client for Birdfy / Netvue."""

from .client import (
    API2_BASE_URL,
    AUTH_RET_CODES,
    CAPI2_BASE_URL,
    CAPIV3_BASE_URL,
    DEFAULT_BASE_URL,
    EVENT_BIRD,
    EVENT_CLIP_READY,
    EVENT_MOTION,
    EVENT_SPECIES,
    SENSITIVE_KEYS,
    BirdfyApiError,
    BirdfyAuthError,
    BirdfyCapabilities,
    BirdfyClient,
    BirdfyConnectionError,
    BirdfyDevice,
    BirdfyError,
    BirdfyEvent,
    BirdfyRateLimitError,
    BirdfyTokens,
    BirdfyUnsupportedError,
    redact_data,
)

__all__ = [
    "API2_BASE_URL",
    "AUTH_RET_CODES",
    "CAPI2_BASE_URL",
    "CAPIV3_BASE_URL",
    "DEFAULT_BASE_URL",
    "EVENT_BIRD",
    "EVENT_CLIP_READY",
    "EVENT_MOTION",
    "EVENT_SPECIES",
    "SENSITIVE_KEYS",
    "BirdfyApiError",
    "BirdfyAuthError",
    "BirdfyCapabilities",
    "BirdfyClient",
    "BirdfyConnectionError",
    "BirdfyDevice",
    "BirdfyError",
    "BirdfyEvent",
    "BirdfyRateLimitError",
    "BirdfyTokens",
    "BirdfyUnsupportedError",
    "redact_data",
]
